# Generated by Django 4.2.7 on 2023-11-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_flight_time',
            field=models.DurationField(),
        ),
    ]
