# Generated by Django 4.2.7 on 2023-11-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_project_max_flight_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='max_flight_time',
            field=models.TimeField(),
        ),
    ]
