# Generated by Django 4.2.7 on 2023-11-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_qualification_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=4)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('has_fueling', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saram', models.IntegerField(unique=True, verbose_name='SARAM')),
                ('cpf', models.IntegerField(unique=True, verbose_name='CPF')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('op_name', models.CharField(max_length=50, verbose_name='Nome de Guerra')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone (WhatsApp)')),
                ('rank', models.CharField(choices=[('TB', 'Tenente-Brigadeiro'), ('MB', 'Major-Brigadeiro'), ('BR', 'Brigadeiro'), ('CL', 'Coronel'), ('TC', 'Tenente-Coronel'), ('MJ', 'Major'), ('CP', 'Capitão'), ('1T', 'Primeiro-Tenente'), ('2T', 'Segundo-Tenente'), ('AP', 'Aspirante'), ('SO', 'Sub-Oficial'), ('1S', 'Primeiro-Sargento'), ('2S', 'Segundo-Sargento'), ('3S', 'Terceiro-Sargento')], max_length=2, verbose_name='Posto / Graduação')),
            ],
        ),
    ]
