# Generated by Django 4.2.7 on 2023-11-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_airport_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='saram',
            field=models.CharField(max_length=8, unique=True, verbose_name='SARAM'),
        ),
    ]
