# Generated by Django 4.2.7 on 2023-11-22 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Matrícula')),
                ('cruise_speed', models.IntegerField(verbose_name='Velocidade de Cruzeiro')),
                ('basic_weight', models.IntegerField(verbose_name='Peso Básico Operacional')),
                ('max_tof_weight', models.IntegerField(verbose_name='Peso Máximo DEP')),
                ('max_ldg_weight', models.IntegerField(verbose_name='Peso Máximo PSO')),
                ('burn_rate', models.IntegerField(verbose_name='Consumo de Combustível')),
                ('max_passengers', models.IntegerField(verbose_name='Número máximo de PAX')),
                ('max_flight_time', models.TimeField(verbose_name='Autonomia')),
            ],
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.RemoveField(
            model_name='project',
            name='basic_weight',
        ),
        migrations.RemoveField(
            model_name='project',
            name='burn_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cruise_speed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='max_flight_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='max_ldg_weight',
        ),
        migrations.RemoveField(
            model_name='project',
            name='max_passengers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='max_tof_weight',
        ),
        migrations.RemoveField(
            model_name='project',
            name='number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='C-XX', max_length=5, verbose_name='Tipo de Aeronave'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airplane',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.project', verbose_name='Tipo de Aeronave'),
        ),
    ]
