# Generated by Django 4.2.7 on 2023-11-22 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_airplane_delete_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='cruise_speed',
            field=models.IntegerField(verbose_name='Velocidade de Cruzeiro (kt)'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='has_fueling',
            field=models.BooleanField(default=False, verbose_name='Abastecimento (CELOG)'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='icao',
            field=models.CharField(max_length=4, verbose_name='Código ICAO'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Tipo de Aeronave'),
        ),
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('IN', 'Piloto Instrutor'), ('PO', 'Piloto Operacional'), ('PB', 'Piloto Básico'), ('AL', 'Piloto-Aluno'), ('IC', 'Mecânico Instrutor'), ('MC', 'Mecânico Operacional'), ('AC', 'Mecânico-Aluno'), ('IF', 'Comissário Instrutor'), ('TF', 'Comissário Operacional'), ('AF', 'Comissário-Aluno')], max_length=2, verbose_name='Operacionalidade')),
                ('last_flight', models.DateField(auto_now_add=True, verbose_name='Data do último voo')),
                ('yearly_hours', models.TimeField(verbose_name='Horas voadas no ano')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.project', verbose_name='Projeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.userprofile')),
            ],
        ),
    ]
