# Generated by Django 4.2.7 on 2023-11-22 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_alter_airplane_cruise_speed_alter_airport_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorprofile',
            name='last_flight',
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='last_flight_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 15, 26, 11, 80436), verbose_name='Data do último voo'),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='yearly_hours',
            field=models.DurationField(verbose_name='Horas voadas no ano'),
        ),
    ]
