# Generated by Django 4.2.7 on 2023-11-22 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_remove_operatorprofile_last_flight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorprofile',
            name='last_flight_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 21, 31, 6, 521631, tzinfo=datetime.timezone.utc), verbose_name='Data do último voo'),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Numeração')),
                ('year', models.IntegerField(default=2023, verbose_name='Ano')),
                ('route', models.JSONField(verbose_name='Rota')),
                ('crew', models.JSONField(verbose_name='Tripulação')),
                ('instructions', models.TextField(max_length=1000, verbose_name='Instruções Especiais')),
                ('airplane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.airplane', verbose_name='Matrícula')),
            ],
        ),
    ]
