# Generated by Django 4.2.7 on 2023-11-22 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_alter_operatorprofile_last_flight_date_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='catering_request',
            field=models.JSONField(blank=True, null=True, verbose_name='Pedido de lanche'),
        ),
        migrations.AddField(
            model_name='mission',
            name='msgr',
            field=models.JSONField(blank=True, null=True, verbose_name='MSGR'),
        ),
        migrations.AddField(
            model_name='mission',
            name='passenger_list',
            field=models.JSONField(blank=True, null=True, verbose_name='Relação de Passageiros'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='instructions',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Instruções Especiais'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='route',
            field=models.JSONField(blank=True, null=True, verbose_name='Rota'),
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='last_flight_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do último voo'),
        ),
    ]
