# Generated by Django 4.2.7 on 2023-11-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_mission_catering_request_mission_msgr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trigram',
            field=models.CharField(default='TST', max_length=3, unique=True, verbose_name='Trigrama'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operatorprofile',
            name='specialty',
            field=models.CharField(choices=[('IN', 'Piloto Instrutor'), ('PO', 'Piloto Operacional'), ('PB', 'Piloto Básico'), ('AL', 'Piloto-Aluno'), ('IC', 'Mecânico Instrutor'), ('MC', 'Mecânico Operacional'), ('AC', 'Mecânico-Aluno'), ('IF', 'Comissário Instrutor'), ('TF', 'Comissário Operacional'), ('AF', 'Comissário-Aluno'), ('IS', 'Instrutor de Lançamento'), ('MS', 'Mestre de Lançamento Op.'), ('AS', 'Aluno de Lançamento')], max_length=2, verbose_name='Operacionalidade'),
        ),
    ]
